# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: African rhapsody

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: server.africanrhapsody.com
        username: ${{ secrets.USERNAME_AFRICAN_RHAPSODY }} 
        password: ${{ secrets.PASSWORD_AFRICAN_RHAPSODY }}
        # port: 21  
        # protocol: ftp
        
    # - name: Use Node.js 18.x
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 18.x
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
